# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
  test_pypi_publish:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: publish to test-pypi
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade build
            python3 -m build
            python3 -m pip install --upgrade twine
            python3 -m twine upload --repository testpypi dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test